[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoints = { khalani = "https://testnet.khalani.network/" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config 